// Coaching for the back-foot defence: what each fault costs, the cue that fixes it, and a
// ladder from shadow work to match pace (shadow → dropped or static ball → throw-downs →
// machine or live), each step with a measurable pass condition.

import type { CoachingEntry } from "./coaching";
import type { Drill } from "./types";

const d = (x: Drill) => x;

export const BFD_COACHING: CoachingEntry[] = [
  {
    metricId: "bfd_back_step",
    low: {
      observation: "Your back foot hardly went back toward the stumps.",
      consequence: "Without going back there's no room: the short ball is met in front of your body, cramped, and gloved or edged to the close fielders.",
      cue: "Back and across first.",
    },
    high: {
      observation: "Your back foot went a long way back, toward the stumps.",
      consequence: "Going too deep takes you onto the stumps and leaves you leaning back: a hit-wicket risk and the ball goes up.",
      cue: "Back and across, not back onto the stumps.",
    },
    drills: [
      d({
        id: "drill_bfd_crease_step",
        level: 1,
        name: "Crease-line step back",
        constraint: "Take your stance with the back foot on a line; shadow the back-foot defence, stepping the back foot back and across so it lands parallel to the crease, inside off stump.",
        dosage: "3 sets × 10 shadows",
        passCondition: "On video, the back foot moves back 10–50 cm (one to two foot-lengths) on 9 of 10, landing parallel to the crease.",
        cue: "Back and across first.",
      }),
      d({
        id: "drill_bfd_chest_drop",
        level: 2,
        name: "Chest-height drop feed",
        constraint: "A partner stands a stride away and drops a ball from above head height so it bounces up to chest height; step back and block it down.",
        dosage: "3 sets × 8 balls",
        passCondition: "The back foot goes back before the bounce on 7 of 8 and the ball lands within 2 m.",
        cue: "Back first, then the bat.",
      }),
      d({
        id: "drill_bfd_short_throws",
        level: 3,
        name: "Short throw-downs",
        constraint: "Throw-downs bouncing short of a length on off stump, rising to the hip or chest.",
        dosage: "4 sets × 6 balls",
        passCondition: "Back foot back and across on 5 of 6, the ball dropped within 2 m, no ball played in the air.",
        cue: "Back and across.",
      }),
      d({
        id: "drill_bfd_machine_short",
        level: 4,
        name: "Machine short of a length",
        constraint: "Bowling machine or live bowler at match pace, short of a length on the stumps.",
        dosage: "3 sets × 6 balls",
        passCondition: "Back foot moves first on 5 of 6, measured on video; no ball fended in the air.",
        cue: "Back and across.",
      }),
    ],
    retest: "Film the next session side-on and check the back foot travels back 5–35% of your height.",
  },
  {
    metricId: "bfd_feet_gap",
    low: { observation: "", consequence: "", cue: "Front foot alongside." },
    high: {
      observation: "Your front foot stayed out in front instead of coming back alongside the back foot.",
      consequence: "With the feet split, your weight is spread and the head tips back: you play the ball away from your eyes and can't get on top of the bounce.",
      cue: "Front foot follows, alongside the back foot.",
    },
    drills: [
      d({
        id: "drill_bfd_together_shadow",
        level: 1,
        name: "Feet-together shadow",
        constraint: "Shadow the back-foot defence; after the back foot steps back, slide the front foot in until the heels are a hand-width apart, front heel up.",
        dosage: "3 sets × 10 shadows",
        passCondition: "Front foot finishes within a foot-length of the back foot on 9 of 10.",
        cue: "Front foot follows.",
      }),
      d({
        id: "drill_bfd_tee_chest",
        level: 2,
        name: "Chest-high tee block",
        constraint: "Ball on a tall tee at chest height, level with your back foot after the step back; block it down past your feet.",
        dosage: "3 sets × 8 blocks",
        passCondition: "Feet together (gap under a foot-length) and the ball dropped within 1 m on 7 of 8.",
        cue: "Back, then together.",
      }),
      d({
        id: "drill_bfd_short_throws_feet",
        level: 3,
        name: "Short throw-downs, feet together",
        constraint: "Short throw-downs on off stump; a coach checks the front foot comes in.",
        dosage: "4 sets × 6 balls",
        passCondition: "Front foot alongside the back foot at contact on 5 of 6, on video.",
        cue: "Front foot alongside.",
      }),
      d({
        id: "drill_bfd_machine_feet",
        level: 4,
        name: "Machine, feet together",
        constraint: "Machine or live bowling, short of a length.",
        dosage: "3 sets × 6 balls",
        passCondition: "Front foot alongside at contact on 5 of 6, the ball dropped dead.",
        cue: "Front foot alongside.",
      }),
    ],
    retest: "Film side-on: at contact the front foot should be within 22% of your height of the back foot.",
  },
  {
    metricId: "bfd_head",
    low: {
      observation: "Your head was behind your back foot at contact: it went back with your weight.",
      consequence: "With the head falling back, the ball is played away from the eyes and the face opens to the sky: it goes up off the bat.",
      cue: "Weight back, head forward.",
    },
    high: {
      observation: "Your head was well forward of your back foot, leaning toward the bowler.",
      consequence: "Leaning forward on a back-foot ball, you meet it early and off balance; the bat can't come down straight under the eyes.",
      cue: "Head over the ball, tall.",
    },
    sideways: {
      low: {
        observation: "Your head was on the leg side of your back foot: falling away from the line of the ball.",
        consequence: "Falling away to the leg side takes the eyes off the line and drags the bat across it: edges behind.",
        cue: "Head inside the line, over the ball.",
      },
      high: {
        observation: "Your head was far to the off side of your back foot, reaching across.",
        consequence: "Reaching across overbalances you to the off side and you play around the ball.",
        cue: "Head over the back foot, in line.",
      },
    },
    drills: [
      d({
        id: "drill_bfd_nose_freeze",
        level: 1,
        name: "Head-forward freeze",
        constraint: "Shadow the back-foot defence in front of a mirror or phone; freeze at contact.",
        dosage: "3 sets × 10 shadows",
        passCondition: "In the freeze your nose is over or just in front of your back toe (side-on), inside the line (from the bowler's end) on 9 of 10.",
        cue: "Weight back, head forward.",
      }),
      d({
        id: "drill_bfd_tee_head",
        level: 2,
        name: "Head-over tee block",
        constraint: "Ball on a chest-high tee level with the back foot; look at the ball through your hands as you block it down.",
        dosage: "3 sets × 8 blocks",
        passCondition: "On video, the head is over or ahead of the back foot at contact on 7 of 8.",
        cue: "Eyes over the ball.",
      }),
      d({
        id: "drill_bfd_throws_head",
        level: 3,
        name: "Short throw-downs, head forward",
        constraint: "Short throw-downs rising to the chest; hold the finish for two seconds.",
        dosage: "4 sets × 6 balls",
        passCondition: "Head ahead of the back foot in the held finish on 5 of 6; no ball goes up.",
        cue: "Head forward, hold it.",
      }),
      d({
        id: "drill_bfd_machine_head",
        level: 4,
        name: "Machine, head forward",
        constraint: "Machine or live bowling short of a length at match pace.",
        dosage: "3 sets × 6 balls",
        passCondition: "Head ahead of the back foot at contact on 5 of 6, on video.",
        cue: "Weight back, head forward.",
      }),
    ],
    retest: "Film side-on: at contact your head should be 2–26% of your height ahead of the back ankle.",
  },
  {
    metricId: "bfd_tall",
    low: { observation: "", consequence: "", cue: "Stay tall." },
    high: {
      observation: "Your head sank from your stance as you played the ball.",
      consequence: "Sinking brings a rising ball up to your gloves and face; you fend at it instead of playing it down.",
      cue: "Stay tall, up on the toes if it bounces.",
    },
    drills: [
      d({
        id: "drill_bfd_tall_shadow",
        level: 1,
        name: "Tall-wall shadow",
        constraint: "Stand side-on to a wall with your head just under a mark at standing height; shadow the back-foot defence without the head dropping from the mark.",
        dosage: "3 sets × 10 shadows",
        passCondition: "The head stays within a hand's width of the mark on 9 of 10.",
        cue: "Stay tall.",
      }),
      d({
        id: "drill_bfd_tennis_bounce",
        level: 2,
        name: "Tennis-ball bounce block",
        constraint: "A partner bounces a tennis ball hard so it rises to chest height; block it down, rising onto the toes if needed.",
        dosage: "3 sets × 8 balls",
        passCondition: "Ball blocked down from above waist height, head no lower than the stance, on 7 of 8.",
        cue: "Get on top of it.",
      }),
      d({
        id: "drill_bfd_throws_tall",
        level: 3,
        name: "Rising throw-downs",
        constraint: "Throw-downs short of a length that rise to the ribs.",
        dosage: "4 sets × 6 balls",
        passCondition: "On video the head drops under 6% of your height at contact on 5 of 6.",
        cue: "Tall and on top.",
      }),
      d({
        id: "drill_bfd_machine_tall",
        level: 4,
        name: "Machine, rising ball",
        constraint: "Machine or live bowling short of a length at match pace.",
        dosage: "3 sets × 6 balls",
        passCondition: "Ball played down from a tall position on 5 of 6.",
        cue: "Stay tall.",
      }),
    ],
    retest: "Film the next session: the head should drop no more than 6% of your height by contact.",
  },
  {
    metricId: "bfd_head_height",
    low: {
      observation: "Your head was low at contact: you crouched.",
      consequence: "Crouching brings a rising ball up to your gloves and face; you fend at it instead of playing it down.",
      cue: "Stay tall.",
    },
    high: { observation: "", consequence: "", cue: "Stay tall." },
    drills: [],
    retest: "Take a side-on photo at contact: your head should be at least 80% of your height above your ankles.",
  },
  {
    metricId: "bfd_elbow",
    low: {
      observation: "Your front elbow was low at contact.",
      consequence: "With the elbow down, the bottom hand takes over and pushes the face up: the ball pops up to short leg or gully.",
      cue: "Front elbow high, handle ahead of the blade.",
    },
    high: {
      observation: "Your front elbow was raised above your shoulder.",
      consequence: "An elbow up by the ear stiffens the arms and closes the face; the bat comes down across the line.",
      cue: "Elbow high but relaxed, level with the shoulder.",
    },
    drills: [
      d({
        id: "drill_bfd_top_hand",
        level: 1,
        name: "Top-hand-only shadow",
        constraint: "Shadow the back-foot defence holding the bat in the top hand only; the front elbow points at the bowler.",
        dosage: "3 sets × 10 shadows",
        passCondition: "Front elbow at or near shoulder height and the face straight down the pitch in 9 of 10 freezes.",
        cue: "Elbow high.",
      }),
      d({
        id: "drill_bfd_top_hand_drop",
        level: 2,
        name: "Top-hand drop feed",
        constraint: "Top hand only (bottom hand behind your back); a partner drops a ball so it bounces to waist-to-chest height.",
        dosage: "3 sets × 8 balls",
        passCondition: "Ball played down within 1 m with the elbow high on 7 of 8.",
        cue: "Top hand leads.",
      }),
      d({
        id: "drill_bfd_throws_elbow",
        level: 3,
        name: "Throw-downs, high elbow",
        constraint: "Short throw-downs, both hands, bottom hand gripping with thumb and finger only.",
        dosage: "4 sets × 6 balls",
        passCondition: "Front elbow within 14% of your height below the shoulder at contact on 5 of 6, ball down.",
        cue: "Elbow high, soft bottom hand.",
      }),
      d({
        id: "drill_bfd_machine_elbow",
        level: 4,
        name: "Machine, high elbow",
        constraint: "Machine or live bowling short of a length.",
        dosage: "3 sets × 6 balls",
        passCondition: "No ball in the air off the face on 6 of 6; elbow high on video.",
        cue: "Elbow high.",
      }),
    ],
    retest: "Film the next session: at contact the front elbow should be no more than 14% of your height below the front shoulder.",
  },
  {
    metricId: "bfd_hands_eyes",
    low: {
      observation: "Your hands were behind your head at contact: the ball was played late, beside you.",
      consequence: "Played that late the bat is still coming down and the ball takes the edge.",
      cue: "Meet it just in front, under the eyes.",
    },
    high: {
      observation: "Your hands were pushed out in front of your head at contact.",
      consequence: "Pushing the hands out opens a gap between bat and body and plays the ball away from the eyes: edges and catches.",
      cue: "Under the eyes, close to the body.",
    },
    sideways: {
      low: {
        observation: "Your hands were to the leg side of your head at contact.",
        consequence: "Playing across the body drags the bat off the line: edges and leg-before.",
        cue: "Hands under the eyes.",
      },
      high: {
        observation: "Your hands were away to the off side of your head at contact, reaching for the ball.",
        consequence: "Reaching away from the body leaves a gap between bat and pad and plays away from the eyes.",
        cue: "Bring the ball to you: under the eyes.",
      },
    },
    drills: [
      d({
        id: "drill_bfd_look_through",
        level: 1,
        name: "Look-through-the-hands shadow",
        constraint: "Shadow the back-foot defence and freeze at contact; you should see the ball's spot through the gap between your hands.",
        dosage: "3 sets × 10 shadows",
        passCondition: "Hands just in front of and under the eyes in 9 of 10 freezes.",
        cue: "Look through the hands.",
      }),
      d({
        id: "drill_bfd_tee_close",
        level: 2,
        name: "Close-tee block",
        constraint: "Ball on a chest-high tee set a forearm's length in front of your back hip; block it straight down.",
        dosage: "3 sets × 8 blocks",
        passCondition: "Ball dropped within 1 m with the hands under the eyes on 7 of 8.",
        cue: "Close to the body.",
      }),
      d({
        id: "drill_bfd_throws_close",
        level: 3,
        name: "Short throw-downs, close to the body",
        constraint: "Short throw-downs; a cone a bat's length in front marks where the ball must stop short of.",
        dosage: "4 sets × 6 balls",
        passCondition: "Ball stops short of the cone on 5 of 6, played under the eyes.",
        cue: "Under the eyes.",
      }),
      d({
        id: "drill_bfd_machine_close",
        level: 4,
        name: "Machine, under the eyes",
        constraint: "Machine or live bowling short of a length on off stump.",
        dosage: "3 sets × 6 balls",
        passCondition: "Ball met under the eyes (on video) and dropped dead on 5 of 6.",
        cue: "Under the eyes.",
      }),
    ],
    retest: "Film the next session: at contact the hands should be within 18% of your height in front of the head.",
  },
  {
    metricId: "bfd_dead_bat",
    low: { observation: "", consequence: "", cue: "Soft hands." },
    high: {
      observation: "Your hands kept moving after contact: you pushed through the ball.",
      consequence: "Pushing through sends the ball on to the close fielders: a catch at short leg, gully or silly point.",
      cue: "Soft hands: let the bat give, then hold.",
    },
    drills: [
      d({
        id: "drill_bfd_hold_shadow",
        level: 1,
        name: "Freeze-and-hold shadow",
        constraint: "Shadow the back-foot defence and hold the contact position still for two seconds.",
        dosage: "3 sets × 10 shadows",
        passCondition: "No movement of the hands after the freeze on 9 of 10.",
        cue: "Play and hold.",
      }),
      d({
        id: "drill_bfd_soft_drop",
        level: 2,
        name: "Soft-hands drop feed",
        constraint: "A partner drops balls to bounce to waist height; the bottom hand holds the bat with thumb and finger only.",
        dosage: "3 sets × 8 balls",
        passCondition: "The ball stops within a bat's length on 7 of 8.",
        cue: "Let the bat give.",
      }),
      d({
        id: "drill_bfd_throws_soft",
        level: 3,
        name: "Bat's-length throw-downs",
        constraint: "Short throw-downs; any ball past a bat's length in front counts as a miss.",
        dosage: "4 sets × 6 balls",
        passCondition: "5 of 6 balls stop within a bat's length.",
        cue: "Soft hands.",
      }),
      d({
        id: "drill_bfd_machine_soft",
        level: 4,
        name: "Machine, ball dropped dead",
        constraint: "Machine or live bowling at match pace, short of a length; close fielders' cones at short leg and gully.",
        dosage: "3 sets × 6 balls",
        passCondition: "No ball carries past the cones on 6 of 6.",
        cue: "Soft hands.",
      }),
    ],
    retest: "Film the next session: the hands should travel under 12% of your height in the quarter second after contact.",
  },
  {
    metricId: "bfd_back_first",
    low: {
      observation: "Your front foot moved and set before your back foot.",
      consequence: "Moving the front foot first rocks the weight back without taking you back and across: you end up stuck on the crease.",
      cue: "Back foot first; the front foot follows.",
    },
    high: {
      observation: "Your front foot came in long after your back foot had set.",
      consequence: "Left behind, the front foot keeps the weight split as the ball arrives.",
      cue: "Back foot, then the front foot straight after.",
    },
    drills: [
      d({
        id: "drill_bfd_one_two",
        level: 1,
        name: "One-two footwork",
        constraint: "Call \"one\" as the back foot goes back and across, \"two\" as the front foot comes alongside; no bat.",
        dosage: "3 sets × 10",
        passCondition: "Back foot always first, front foot within a quarter second, on 10 of 10.",
        cue: "One, two.",
      }),
      d({
        id: "drill_bfd_one_two_drop",
        level: 2,
        name: "One-two drop feed",
        constraint: "The same footwork to a ball dropped to bounce to chest height, then the block.",
        dosage: "3 sets × 8 balls",
        passCondition: "Back foot first and set before the bounce on 7 of 8.",
        cue: "One, two, block.",
      }),
      d({
        id: "drill_bfd_one_two_throws",
        level: 3,
        name: "One-two throw-downs",
        constraint: "Short throw-downs; the feeder only throws once you are in the stance.",
        dosage: "4 sets × 6 balls",
        passCondition: "On video, the front foot sets 0–350 ms after the back foot on 5 of 6.",
        cue: "One, two.",
      }),
      d({
        id: "drill_bfd_one_two_machine",
        level: 4,
        name: "One-two at pace",
        constraint: "Machine or live bowling short of a length.",
        dosage: "3 sets × 6 balls",
        passCondition: "Back foot first on 5 of 6, on video.",
        cue: "Back first.",
      }),
    ],
    retest: "Film the next session: the front foot should set 0–350 ms after the back foot.",
  },
  {
    metricId: "bfd_set_late",
    low: { observation: "", consequence: "", cue: "Set early." },
    high: {
      observation: "You were still moving when the ball arrived.",
      consequence: "Still moving at contact, the bat chases the ball and the head moves: edges and mistimed blocks.",
      cue: "Back early, still at contact.",
    },
    drills: [
      d({
        id: "drill_bfd_early_shadow",
        level: 1,
        name: "Early-set shadow",
        constraint: "A partner claps the moment of release; you must be back, still and in position by a second clap half a second later.",
        dosage: "3 sets × 10",
        passCondition: "Still at the second clap on 9 of 10.",
        cue: "Early and still.",
      }),
      d({
        id: "drill_bfd_early_drop",
        level: 2,
        name: "Early-set drop feed",
        constraint: "The partner shows the ball, then drops it after a short pause; set before it bounces.",
        dosage: "3 sets × 8 balls",
        passCondition: "Set before the bounce on 7 of 8.",
        cue: "Set, then play.",
      }),
      d({
        id: "drill_bfd_early_throws",
        level: 3,
        name: "Early-set throw-downs",
        constraint: "Short throw-downs with a quicker arm from a shorter distance.",
        dosage: "4 sets × 6 balls",
        passCondition: "On video, still before contact on 5 of 6.",
        cue: "Early.",
      }),
      d({
        id: "drill_bfd_early_machine",
        level: 4,
        name: "Early set at pace",
        constraint: "Machine or live bowling short of a length at match pace.",
        dosage: "3 sets × 6 balls",
        passCondition: "Set before contact on 5 of 6, on video.",
        cue: "Early and still.",
      }),
    ],
    retest: "Film the next session with the ball in view: every part should be set before contact.",
  },
];
