// The back-foot defence's measures: what each one is, why it matters and its range. Ranges
// are coaching geometry (docs/11-back-foot-defence.md): no lab measurements of the shot were
// found. Provisional, and labelled so wherever they are shown.

import type { MetricDefinition } from "./registry";

export const BFD_METRIC_VERSION = "bfd-0.1.0";

export const BFD_SOURCE =
  "Coaching geometry for the back-foot defence (back and across, front foot alongside, head forward over the back foot, tall, high front elbow, contact under the eyes, soft hands; Sportplan, ESPNcricinfo and Pitchero coaching pages). Provisional: not yet fitted to measured players.";

/** Bands × stature from the back ankle (+ toward the bowler side-on, + toward the off side from either end). */
export const BFD_BANDS = {
  backStep: [0.05, 0.35],
  feetGap: [0, 0.22],
  // Side-on: from over the back foot to just past the front foot (alongside it, up to 0.22 ahead).
  head: { forward: [0.02, 0.26], sideways: [-0.04, 0.16] },
  headDrop: [-0.06, 0.06],
  elbow: [-0.14, 0.04],
  handsEyes: { forward: [-0.04, 0.18], sideways: [-0.08, 0.1] },
  deadBat: [0, 0.12],
  backFirstMs: [0, 350],
  setLateMs: [-400, 0],
  headHeight: [0.8, 1.0],
} as const;

export const BFD_METRICS: MetricDefinition[] = [
  {
    id: "bfd_back_step",
    name: "Back foot back",
    domain: "footwork",
    unit: "× stature",
    decimals: 2,
    phase: "Back-foot movement",
    meaning: "How far your back foot moved back toward the stumps before the ball arrived (side-on).",
    relevance: "Going back makes room: the short ball is met under the eyes instead of in front of the body. Staying where you are leaves you cramped and fending.",
    range: { lo: BFD_BANDS.backStep[0], hi: BFD_BANDS.backStep[1] },
    requires: ["body", "side_view"],
    weight: 1.2,
    direction: "band",
    only: "video",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_feet_gap",
    name: "Front foot alongside",
    domain: "footwork",
    unit: "× stature",
    decimals: 2,
    phase: "Contact",
    meaning: "How far your front foot is from your back foot along the pitch at contact (side-on).",
    relevance: "The front foot follows the back foot and comes alongside it, so the body stays balanced and side-on over the back foot. Left out in front, it splits the weight and pulls the head back.",
    range: { lo: BFD_BANDS.feetGap[0], hi: BFD_BANDS.feetGap[1] },
    requires: ["body", "contact", "side_view"],
    weight: 0.9,
    direction: "lower",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_head",
    name: "Head forward over the back foot",
    domain: "alignment",
    unit: "× stature",
    decimals: 2,
    phase: "Contact",
    meaning: "Where your head is relative to your back ankle at contact. Side-on: how far forward of it (toward the bowler). From either end of the pitch: how far toward the off side, over the line of the ball.",
    relevance: "The weight goes back but the head stays forward, over the ball and in its line. A head that falls back with the weight sends the ball up off the face.",
    range: { lo: BFD_BANDS.head.forward[0], hi: BFD_BANDS.head.forward[1] },
    rangeSideways: { lo: BFD_BANDS.head.sideways[0], hi: BFD_BANDS.head.sideways[1] },
    requires: ["body", "contact"],
    weight: 1.4,
    direction: "band",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_tall",
    name: "Standing tall",
    domain: "head_trunk",
    unit: "× stature",
    decimals: 2,
    phase: "Contact",
    meaning: "How far your head dropped from your stance by contact (+ lower, − higher: up on the toes).",
    relevance: "The back-foot defence meets a rising ball: you stay tall, even rise onto the toes, to get on top of it. Sinking brings the ball up to the face and the gloves.",
    range: { lo: BFD_BANDS.headDrop[0], hi: BFD_BANDS.headDrop[1] },
    requires: ["body", "contact"],
    weight: 1,
    direction: "band",
    only: "video",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_head_height",
    name: "Standing tall",
    domain: "head_trunk",
    unit: "× stature",
    decimals: 2,
    phase: "Contact",
    meaning: "How high your head is above your ankles at contact, as a share of your standing height (standing straight: about 90%).",
    relevance: "The back-foot defence meets a rising ball: you stay tall to get on top of it. Crouching brings the ball up to the face and the gloves.",
    range: { lo: BFD_BANDS.headHeight[0], hi: BFD_BANDS.headHeight[1] },
    requires: ["body", "contact"],
    weight: 1,
    direction: "higher",
    only: "photo",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_elbow",
    name: "Front elbow high",
    domain: "bat_contact",
    unit: "× stature",
    decimals: 2,
    phase: "Contact",
    meaning: "How high your front elbow is compared with your front shoulder at contact (0 = level; − below it).",
    relevance: "A high front elbow keeps the full face of the bat straight down the pitch and the handle ahead of the blade, so the ball goes down. A low elbow lets the bottom hand push the face up.",
    range: { lo: BFD_BANDS.elbow[0], hi: BFD_BANDS.elbow[1] },
    requires: ["body", "contact"],
    weight: 1.1,
    direction: "band",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_hands_eyes",
    name: "Contact under the eyes",
    domain: "bat_contact",
    unit: "× stature",
    decimals: 2,
    phase: "Contact",
    meaning: "Where your hands are relative to your head at contact. Side-on: how far in front of it. From either end: how far to the side of it.",
    relevance: "The ball is met close to the body, straight under the eyes, looking through the hands. Pushing the hands out in front, or away from the body, opens the gate between bat and body.",
    range: { lo: BFD_BANDS.handsEyes.forward[0], hi: BFD_BANDS.handsEyes.forward[1] },
    rangeSideways: { lo: BFD_BANDS.handsEyes.sideways[0], hi: BFD_BANDS.handsEyes.sideways[1] },
    requires: ["body", "contact"],
    weight: 1,
    direction: "band",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_dead_bat",
    name: "Soft hands",
    domain: "bat_contact",
    unit: "× stature",
    decimals: 2,
    phase: "After contact",
    meaning: "How far your hands travelled in the quarter second after contact.",
    relevance: "Soft hands let the bat give, so the ball drops dead in front of you. Pushing through it sends a catch to the close fielders.",
    range: { lo: BFD_BANDS.deadBat[0], hi: BFD_BANDS.deadBat[1] },
    requires: ["body", "contact"],
    weight: 1,
    direction: "lower",
    only: "video",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_back_first",
    name: "Back foot first",
    domain: "sequence",
    unit: "ms",
    decimals: 0,
    phase: "Back-foot movement",
    meaning: "How long after your back foot set your front foot set (− the front foot set first).",
    relevance: "The back foot moves first and the front foot follows it in. Moving the front foot first rocks the weight back without taking you back and across.",
    range: { lo: BFD_BANDS.backFirstMs[0], hi: BFD_BANDS.backFirstMs[1] },
    requires: ["body", "contact"],
    weight: 0.8,
    direction: "band",
    only: "video",
    basis: BFD_SOURCE,
  },
  {
    id: "bfd_set_late",
    name: "Set before the ball arrives",
    domain: "sequence",
    unit: "ms",
    decimals: 0,
    phase: "Contact",
    meaning: "When the last of your back foot, front foot and head stopped moving, relative to contact (− before it).",
    relevance: "Set early, you play the ball from a still base with the head steady. Still moving as it arrives, the bat chases the ball.",
    range: { lo: BFD_BANDS.setLateMs[0], hi: BFD_BANDS.setLateMs[1] },
    requires: ["body", "contact"],
    weight: 0.8,
    direction: "lower",
    only: "video",
    basis: BFD_SOURCE,
  },
];

export const BFD_IDS = BFD_METRICS.map((m) => m.id);
/** One photo, taken to be contact: the position checks a single side-on frame can make. */
export const BFD_POSITION_FORMULA = ["bfd_feet_gap", "bfd_head", "bfd_head_height", "bfd_elbow", "bfd_hands_eyes"];
/** From either end of the pitch the forward distances run toward the camera: these remain. */
export const BFD_FRONT_FORMULA = ["bfd_head", "bfd_head_height", "bfd_elbow", "bfd_hands_eyes"];
